import { FastifyInstance } from 'fastify'
import { query, queryOne, execute } from '../db.js'
import { requireAuth } from '../middleware/auth.js'
import { writeAuditLog } from '../audit/middleware.js'
import { validateRecord } from './validators.js'
import { broadcast } from '../ws/hub.js'
import { parseZoneFile } from './parseZone.js'

const NS_RECORDS: string[] = (process.env.NS_RECORDS ?? '').split(',').map(s => s.trim()).filter(Boolean)

// ── Inline zone renderer (mirrors worker/src/renderZone.ts) ──
function _fqdn(v: string): string {
  if (v === '@' || v === '') return v
  return v.endsWith('.') ? v : `${v}.`
}
function _formatTxt(raw: string): string {
  const stripped = raw.replace(/^"|"$/g, '')
  const chunks: string[] = []
  for (let i = 0; i < stripped.length; i += 255) chunks.push(`"${stripped.slice(i, i + 255)}"`)
  return chunks.join(' ')
}
function _renderRecord(rec: any, defaultTtl: number): string {
  const ttl = rec.ttl ?? defaultTtl
  const name = rec.name === '@' ? '@' : rec.name
  switch (rec.type) {
    case 'A': case 'AAAA': case 'PTR': return `${name} ${ttl} IN ${rec.type} ${rec.value}`
    case 'CNAME': case 'NS': return `${name} ${ttl} IN ${rec.type} ${_fqdn(rec.value)}`
    case 'MX': return `${name} ${ttl} IN MX ${rec.priority ?? 10} ${_fqdn(rec.value)}`
    case 'TXT': return `${name} ${ttl} IN TXT ${_formatTxt(rec.value)}`
    case 'SRV': return `${name} ${ttl} IN SRV ${rec.priority ?? 0} ${rec.weight ?? 0} ${rec.port ?? 0} ${_fqdn(rec.value)}`
    default: return `${name} ${ttl} IN ${rec.type} ${rec.value}`
  }
}
function renderZoneText(domain: any, records: any[], soa: any, serial: number): string {
  const lines: string[] = []
  lines.push(`; Zone: ${domain.fqdn}`)
  lines.push(`; Generated by INFOdns Worker at ${new Date().toISOString()}`)
  lines.push(`; DO NOT EDIT MANUALLY`)
  lines.push('')
  lines.push(`$ORIGIN ${_fqdn(domain.fqdn)}`)
  lines.push(`$TTL ${domain.default_ttl}`)
  lines.push('')
  lines.push(`@ IN SOA ${_fqdn(soa.mname)} ${_fqdn(soa.rname)} (`)
  lines.push(`    ${serial}   ; serial`)
  lines.push(`    ${soa.refresh}        ; refresh`)
  lines.push(`    ${soa.retry}         ; retry`)
  lines.push(`    ${soa.expire}      ; expire`)
  lines.push(`    ${soa.minimum_ttl} ) ; minimum TTL`)
  lines.push('')
  for (const ns of NS_RECORDS) lines.push(`@ IN NS ${_fqdn(ns)}`)
  lines.push('')
  const byType = new Map<string, any[]>()
  for (const rec of records) {
    const list = byType.get(rec.type) ?? []
    list.push(rec)
    byType.set(rec.type, list)
  }
  for (const [type, recs] of byType) {
    lines.push(`; ${type}`)
    for (const rec of recs) lines.push(_renderRecord(rec, domain.default_ttl))
    lines.push('')
  }
  return lines.join('\n')
}

/** Enqueue a zone render job for a domain (upsert — one pending job per domain) */
async function enqueueRender(domainId: number) {
  await execute(
    `INSERT INTO zone_render_queue (domain_id, status) VALUES (?, 'pending')
     ON DUPLICATE KEY UPDATE status = IF(status = 'processing', status, 'pending'), updated_at = NOW()`,
    [domainId]
  )
  await execute("UPDATE domains SET zone_status = 'dirty' WHERE id = ?", [domainId])
}

/** Resolve domain and enforce ownership */
async function resolveDomain(domainId: string, req: any, reply: any) {
  const ownerClause = req.user.role === 'admin' ? '' : ` AND customer_id IN (SELECT customer_id FROM user_customers WHERE user_id = ${Number(req.user.sub)})`
  const domain = await queryOne(
    `SELECT id, customer_id FROM domains WHERE id = ? AND status != 'deleted'${ownerClause}`,
    [domainId]
  )
  if (!domain) { reply.status(404).send({ code: 'NOT_FOUND' }); return null }
  return domain as { id: number; customer_id: number }
}

export async function recordRoutes(app: FastifyInstance) {
  // GET /domains/:domainId/records
  app.get<{ Params: { domainId: string } }>(
    '/domains/:domainId/records',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const records = await (await import('../db.js')).query(
        `SELECT id, name, type, ttl, priority, weight, port, value, created_at, updated_at
         FROM dns_records WHERE domain_id = ? AND is_deleted = 0 ORDER BY type, name`,
        [domain.id]
      )
      return records
    }
  )

  // POST /domains/:domainId/records
  app.post<{ Params: { domainId: string } }>(
    '/domains/:domainId/records',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const validation = validateRecord(req.body)
      if (!validation.success) return reply.status(400).send({ code: 'VALIDATION_ERROR', message: validation.error })

      const { name, type, ttl, priority, weight, port, value } = validation.data
      const result = await execute(
        `INSERT INTO dns_records (domain_id, name, type, ttl, priority, weight, port, value)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [domain.id, name, type, ttl ?? null, priority ?? null, weight ?? null, port ?? null, value]
      )
      await enqueueRender(domain.id)
      broadcast({ type: 'record_changed', domainId: domain.id })

      const created = await queryOne('SELECT * FROM dns_records WHERE id = ?', [result.insertId])
      await writeAuditLog({ req, entityType: 'dns_record', entityId: result.insertId, domainId: domain.id, action: 'create', newValue: created })
      return reply.status(201).send(created)
    }
  )

  // PUT /domains/:domainId/records/:id
  app.put<{ Params: { domainId: string; id: string } }>(
    '/domains/:domainId/records/:id',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const old = await queryOne(
        'SELECT * FROM dns_records WHERE id = ? AND domain_id = ? AND is_deleted = 0',
        [req.params.id, domain.id]
      )
      if (!old) return reply.status(404).send({ code: 'NOT_FOUND' })

      const validation = validateRecord({ ...(old as any), ...(req.body as any) })
      if (!validation.success) return reply.status(400).send({ code: 'VALIDATION_ERROR', message: validation.error })

      const { name, type, ttl, priority, weight, port, value } = validation.data
      await execute(
        `UPDATE dns_records SET name=?, type=?, ttl=?, priority=?, weight=?, port=?, value=? WHERE id=?`,
        [name, type, ttl ?? null, priority ?? null, weight ?? null, port ?? null, value, req.params.id]
      )
      await enqueueRender(domain.id)
      broadcast({ type: 'record_changed', domainId: domain.id })

      const updated = await queryOne('SELECT * FROM dns_records WHERE id = ?', [req.params.id])
      await writeAuditLog({ req, entityType: 'dns_record', entityId: Number(req.params.id), domainId: domain.id, action: 'update', oldValue: old, newValue: updated })
      return updated
    }
  )

  // DELETE /domains/:domainId/records/:id
  app.delete<{ Params: { domainId: string; id: string } }>(
    '/domains/:domainId/records/:id',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const old = await queryOne(
        'SELECT * FROM dns_records WHERE id = ? AND domain_id = ? AND is_deleted = 0',
        [req.params.id, domain.id]
      )
      if (!old) return reply.status(404).send({ code: 'NOT_FOUND' })

      await execute('UPDATE dns_records SET is_deleted = 1 WHERE id = ?', [req.params.id])
      await enqueueRender(domain.id)
      broadcast({ type: 'record_changed', domainId: domain.id })
      await writeAuditLog({ req, entityType: 'dns_record', entityId: Number(req.params.id), domainId: domain.id, action: 'delete', oldValue: old })
      return { ok: true }
    }
  )

  // GET /domains/:domainId/zone-text  — re-renders zone from DB for inspection
  app.get<{ Params: { domainId: string } }>(
    '/domains/:domainId/zone-text',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const domainData = await queryOne<{ fqdn: string; default_ttl: number; customer_id: number; last_serial: number }>(
        'SELECT fqdn, default_ttl, customer_id, last_serial FROM domains WHERE id = ?',
        [domain.id]
      )
      if (!domainData) return reply.status(404).send({ code: 'NOT_FOUND' })

      const records = await query(
        'SELECT name, type, ttl, priority, weight, port, value FROM dns_records WHERE domain_id = ? AND is_deleted = 0 ORDER BY type, name',
        [domain.id]
      )

      const soa = await queryOne<{ mname: string; rname: string; refresh: number; retry: number; expire: number; minimum_ttl: number }>(
        `SELECT mname, rname, refresh, retry, expire, minimum_ttl
         FROM soa_templates WHERE customer_id = ? OR customer_id IS NULL
         ORDER BY customer_id DESC LIMIT 1`,
        [domainData.customer_id]
      )
      if (!soa) return reply.status(500).send({ code: 'NO_SOA_TEMPLATE' })

      const text = renderZoneText(domainData, records, soa, domainData.last_serial ?? 0)
      return { text }
    }
  )

  // POST /domains/:domainId/zone-import/parse
  app.post<{ Params: { domainId: string } }>(
    '/domains/:domainId/zone-import/parse',
    { preHandler: requireAuth },
    async (req, reply) => {
      const domain = await resolveDomain(req.params.domainId, req, reply)
      if (!domain) return

      const domainData = await queryOne<{ fqdn: string; default_ttl: number }>(
        'SELECT fqdn, default_ttl FROM domains WHERE id = ?',
        [domain.id]
      )
      if (!domainData) return reply.status(404).send({ code: 'NOT_FOUND' })

      // Read uploaded file
      let fileText = ''
      try {
        for await (const part of (req as any).files()) {
          const chunks: Buffer[] = []
          for await (const chunk of part.file) chunks.push(chunk as Buffer)
          fileText = Buffer.concat(chunks).toString('utf8')
          break // only process first file
        }
      } catch (err: any) {
        if (err.code === 'FST_REQ_FILE_TOO_LARGE') {
          return reply.status(400).send({ code: 'PARSE_ERROR', message: 'File too large (max 20 MB)' })
        }
        throw err
      }

      if (!fileText.trim()) {
        return reply.status(400).send({ code: 'PARSE_ERROR', message: 'Empty or unreadable file' })
      }

      const { records: parsed, skipped } = parseZoneFile(fileText, domainData.fqdn, domainData.default_ttl)

      if (parsed.length === 0 && skipped.length === 0) {
        return reply.status(400).send({ code: 'PARSE_ERROR', message: 'No DNS records found in file' })
      }

      // Fetch existing records for conflict detection
      const existing = await query<any>(
        'SELECT id, name, type, ttl, priority, weight, port, value FROM dns_records WHERE domain_id = ? AND is_deleted = 0',
        [domain.id]
      )

      // Partition parsed records into new vs conflicts
      const newRecords = []
      const conflicts = []

      for (const rec of parsed) {
        const matches = existing.filter((e: any) => e.name === rec.name && e.type === rec.type)
        if (matches.length === 0) {
          newRecords.push(rec)
        } else {
          // Pair incoming with first matching existing record
          conflicts.push({ existing: matches[0], incoming: rec })
        }
      }

      return { new: newRecords, conflicts, skipped }
    }
  )
}
