import { createHash } from 'crypto'

const SOA_MNAME = process.env.SOA_MNAME ?? 'ns1.ns.inforant.de.'
const SOA_RNAME = process.env.SOA_RNAME ?? 'hostmaster.inforant.de.'

/**
 * Generate a unique label for a member zone in the catalog.
 * Uses first 40 chars of SHA-1 hex digest of the zone name.
 */
function memberHash(fqdn: string): string {
  return createHash('sha1').update(fqdn).digest('hex').slice(0, 40)
}

/**
 * Renders a BIND catalog zone file (RFC 9432).
 *
 * The catalog zone contains PTR records that list all member zones.
 * Secondaries configured to watch this catalog will automatically
 * create/remove secondary zone entries as zones are added/removed.
 */
export function renderCatalogZone(
  catalogName: string,
  memberZones: string[],
  serial: number,
): string {
  const lines: string[] = []

  lines.push(`; Catalog zone: ${catalogName}`)
  lines.push(`; Generated by INFOdns Worker at ${new Date().toISOString()}`)
  lines.push(`; DO NOT EDIT MANUALLY`)
  lines.push('')
  lines.push(`$ORIGIN ${catalogName}.`)
  lines.push(`$TTL 3600`)
  lines.push('')

  // SOA
  lines.push(`@ IN SOA ${SOA_MNAME} ${SOA_RNAME} (`)
  lines.push(`    ${serial}   ; serial`)
  lines.push(`    3600        ; refresh`)
  lines.push(`    1800        ; retry`)
  lines.push(`    604800      ; expire`)
  lines.push(`    86400 )     ; minimum TTL`)
  lines.push('')

  // NS (required but not used for transfers — catalog zones are transferred via AXFR)
  lines.push(`@ IN NS invalid.`)
  lines.push('')

  // Catalog zone version (required by RFC 9432)
  lines.push(`version IN TXT "2"`)
  lines.push('')

  // Member zones as PTR records
  lines.push(`; Member zones`)
  for (const fqdn of memberZones) {
    const hash = memberHash(fqdn)
    lines.push(`${hash}.zones IN PTR ${fqdn}.`)
  }
  lines.push('')

  return lines.join('\n')
}
