import { open, readFile } from 'fs/promises'
import { join } from 'path'
import { rndcReconfig, rndcReload } from './deployZone.js'
import { renderCatalogZone } from './catalogZone.js'
import { writeAtomic } from './deployZone.js'

/**
 * Write content to destPath in-place (truncate + write + fsync).
 * We deliberately do NOT rename here because Docker bind-mounted files
 * are referenced by inode — rename() creates a new inode that the
 * container does not see until it is restarted.
 */
async function writeConf(destPath: string, content: string): Promise<void> {
  const fh = await open(destPath, 'w')
  try {
    await fh.writeFile(content, 'utf8')
    await fh.sync()
  } finally {
    await fh.close()
  }
}

const CONF_BASE      = process.env.CONF_BASE             ?? '/bind'
const PRIMARY_HOST   = process.env.BIND_PRIMARY_HOST     ?? 'bind-primary'
const RNDC_PORT      = process.env.BIND_PRIMARY_RNDC_PORT ?? '953'
const CATALOG_ZONE   = process.env.CATALOG_ZONE          ?? 'catalog.dns.inforant.de'
const ZONE_DIR       = process.env.ZONE_DIR              ?? '/bind/primary/zones'

// Real secondary server IPs (ns1, ns2) for also-notify — no Docker hostnames needed
const SECONDARY_IPS: string[] = (process.env.SECONDARY_IPS ?? '')
  .split(',').map(s => s.trim()).filter(Boolean)

interface ZoneEntry {
  fqdn: string
  dnssec_enabled: boolean
}

async function writePrimaryConf(zones: ZoneEntry[]): Promise<void> {
  const confPath = join(CONF_BASE, 'primary', 'conf', 'named.conf.local')

  const notifyList = SECONDARY_IPS.map(ip => `${ip};`).join(' ')

  const lines = [
    '// Generated by INFORENT Prisma Worker — do not edit manually',
    `// Updated: ${new Date().toISOString()}`,
    '',
    `// Catalog zone — secondaries discover member zones via this`,
    `zone "${CATALOG_ZONE}" {`,
    `    type primary;`,
    `    file "/zones/${CATALOG_ZONE}.zone";`,
    `    allow-transfer { key tsig-secondary; };`,
    `    notify yes;`,
    ...(notifyList ? [`    also-notify { ${notifyList} };`] : []),
    `};`,
    '',
  ]

  for (const zone of zones) {
    lines.push(`zone "${zone.fqdn}" {`)
    lines.push(`    type primary;`)
    lines.push(`    file "/zones/${zone.fqdn}.zone";`)
    if (zone.dnssec_enabled) {
      lines.push(`    dnssec-policy "default";`)
      lines.push(`    inline-signing yes;`)
      lines.push(`    key-directory "/var/cache/bind/keys";`)
    }
    lines.push(`    allow-transfer { key tsig-secondary; };`)
    lines.push(`    notify yes;`)
    if (notifyList) lines.push(`    also-notify { ${notifyList} };`)
    lines.push(`};`)
    lines.push('')
  }

  await writeConf(confPath, lines.join('\n'))
}

/**
 * Generate a catalog zone serial that always increments.
 * Uses Unix timestamp (seconds since epoch) as the floor.
 */
async function catalogSerial(zonePath: string): Promise<number> {
  const unixNow = Math.floor(Date.now() / 1000)

  try {
    const content = await readFile(zonePath, 'utf8')
    const match = content.match(/(\d+)\s*;\s*serial/)
    if (match) {
      const current = Number(match[1])
      return Math.max(current + 1, unixNow)
    }
  } catch {
    // File doesn't exist yet
  }
  return unixNow
}

async function deployCatalogZone(zones: ZoneEntry[]): Promise<void> {
  const zonePath = join(ZONE_DIR, `${CATALOG_ZONE}.zone`)
  const serial = await catalogSerial(zonePath)
  const content = renderCatalogZone(CATALOG_ZONE, zones.map(z => z.fqdn), serial)
  await writeAtomic(zonePath, content)
}

export async function regenerateNamedConf(zones: ZoneEntry[]): Promise<void> {
  await writePrimaryConf(zones)
  await deployCatalogZone(zones)

  await rndcReconfig(PRIMARY_HOST, RNDC_PORT).catch(err =>
    console.error(`[namedConf] rndc reconfig ${PRIMARY_HOST} failed:`, err.message)
  )
  // Reload catalog zone so secondaries pick up membership changes
  await rndcReload(CATALOG_ZONE).catch(err =>
    console.error(`[namedConf] rndc reload ${CATALOG_ZONE} failed:`, err.message)
  )
}
