import { open, readFile } from 'fs/promises'
import { join } from 'path'
import { rndcReconfig, rndcReload } from './deployZone.js'
import { renderCatalogZone } from './catalogZone.js'
import { writeAtomic } from './deployZone.js'

/**
 * Write content to destPath in-place (truncate + write + fsync).
 * We deliberately do NOT rename here because Docker bind-mounted files
 * are referenced by inode — rename() creates a new inode that the
 * container does not see until it is restarted.
 */
async function writeConf(destPath: string, content: string): Promise<void> {
  const fh = await open(destPath, 'w')
  try {
    await fh.writeFile(content, 'utf8')
    await fh.sync()
  } finally {
    await fh.close()
  }
}

const CONF_BASE      = process.env.CONF_BASE             ?? '/bind'
const PRIMARY_HOST   = process.env.BIND_PRIMARY_HOST     ?? 'bind-primary'
const RNDC_PORT      = process.env.BIND_PRIMARY_RNDC_PORT ?? '953'
const CATALOG_ZONE   = process.env.CATALOG_ZONE          ?? 'catalog.dns.inforant.de'
const ZONE_DIR       = process.env.ZONE_DIR              ?? '/bind/primary/zones'

// Real secondary server IPs (ns1, ns2) for also-notify — no Docker hostnames needed
const SECONDARY_IPS: string[] = (process.env.SECONDARY_IPS ?? '')
  .split(',').map(s => s.trim()).filter(Boolean)

async function writePrimaryConf(zones: string[]): Promise<void> {
  const confPath = join(CONF_BASE, 'primary', 'conf', 'named.conf.local')

  const notifyList = SECONDARY_IPS.map(ip => `${ip};`).join(' ')

  const lines = [
    '// Generated by INFOdns Worker — do not edit manually',
    `// Updated: ${new Date().toISOString()}`,
    '',
    `// Catalog zone — secondaries discover member zones via this`,
    `zone "${CATALOG_ZONE}" {`,
    `    type primary;`,
    `    file "/zones/${CATALOG_ZONE}.zone";`,
    `    allow-transfer { key tsig-secondary; };`,
    `    notify yes;`,
    ...(notifyList ? [`    also-notify { ${notifyList} };`] : []),
    `};`,
    '',
  ]

  for (const fqdn of zones) {
    lines.push(`zone "${fqdn}" {`)
    lines.push(`    type primary;`)
    lines.push(`    file "/zones/${fqdn}.zone";`)
    lines.push(`    allow-transfer { key tsig-secondary; };`)
    lines.push(`    notify yes;`)
    if (notifyList) lines.push(`    also-notify { ${notifyList} };`)
    lines.push(`};`)
    lines.push('')
  }

  await writeConf(confPath, lines.join('\n'))
}

/**
 * Generate a catalog zone serial that always increments.
 * Reads the current serial from the existing zone file and bumps it.
 * Falls back to YYYYMMDDnn format if no file exists yet.
 */
async function catalogSerial(zonePath: string): Promise<number> {
  const now = new Date()
  const date = now.toISOString().slice(0, 10).replace(/-/g, '')
  const baseSerial = Number(`${date}00`)

  try {
    const content = await readFile(zonePath, 'utf8')
    const match = content.match(/(\d{10})\s*;\s*serial/)
    if (match) {
      const current = Number(match[1])
      // If same day, increment; if new day, use base
      return Math.max(current + 1, baseSerial)
    }
  } catch {
    // File doesn't exist yet
  }
  return baseSerial
}

async function deployCatalogZone(zones: string[]): Promise<void> {
  const zonePath = join(ZONE_DIR, `${CATALOG_ZONE}.zone`)

  // Only bump serial when member list actually changed
  let serial: number
  try {
    const existing = await readFile(zonePath, 'utf8')
    const existingMembers = [...existing.matchAll(/\.zones\s+IN\s+PTR\s+(\S+)/g)]
      .map(m => m[1]).sort()
    const newMembers = zones.map(z => `${z}.`).sort()
    if (existingMembers.join(',') === newMembers.join(',')) {
      // Same members — keep current serial (no transfer needed)
      const match = existing.match(/(\d{10})\s*;\s*serial/)
      serial = match ? Number(match[1]) : await catalogSerial(zonePath)
    } else {
      serial = await catalogSerial(zonePath)
    }
  } catch {
    serial = await catalogSerial(zonePath)
  }

  const content = renderCatalogZone(CATALOG_ZONE, zones, serial)
  await writeAtomic(zonePath, content)
}

export async function regenerateNamedConf(zones: string[]): Promise<void> {
  await writePrimaryConf(zones)
  await deployCatalogZone(zones)

  await rndcReconfig(PRIMARY_HOST, RNDC_PORT).catch(err =>
    console.error(`[namedConf] rndc reconfig ${PRIMARY_HOST} failed:`, err.message)
  )
  // Reload catalog zone so secondaries pick up membership changes
  await rndcReload(CATALOG_ZONE).catch(err =>
    console.error(`[namedConf] rndc reload ${CATALOG_ZONE} failed:`, err.message)
  )
}
