import { open } from 'fs/promises'
import { join } from 'path'
import { rndcReconfig } from './deployZone.js'

/**
 * Write content to destPath in-place (truncate + write + fsync).
 * We deliberately do NOT rename here because Docker bind-mounted files
 * are referenced by inode — rename() creates a new inode that the
 * container does not see until it is restarted.
 */
async function writeConf(destPath: string, content: string): Promise<void> {
  const fh = await open(destPath, 'w')
  try {
    await fh.writeFile(content, 'utf8')
    await fh.sync()
  } finally {
    await fh.close()
  }
}

const CONF_BASE    = process.env.CONF_BASE             ?? '/bind'
const PRIMARY_HOST = process.env.BIND_PRIMARY_HOST     ?? 'bind-primary'
const RNDC_PORT    = process.env.BIND_PRIMARY_RNDC_PORT ?? '953'

// Real secondary server IPs (hil1, hel1) for also-notify — no Docker hostnames needed
const SECONDARY_IPS: string[] = (process.env.SECONDARY_IPS ?? '')
  .split(',').map(s => s.trim()).filter(Boolean)

async function writePrimaryConf(zones: string[]): Promise<void> {
  const confPath = join(CONF_BASE, 'primary', 'conf', 'named.conf.local')

  const notifyList = SECONDARY_IPS.map(ip => `${ip};`).join(' ')

  const lines = [
    '// Generated by INFOdns Worker — do not edit manually',
    `// Updated: ${new Date().toISOString()}`,
    '',
  ]

  for (const fqdn of zones) {
    lines.push(`zone "${fqdn}" {`)
    lines.push(`    type primary;`)
    lines.push(`    file "/var/lib/bind/zones/${fqdn}.zone";`)
    lines.push(`    allow-transfer { key tsig-secondary; };`)
    lines.push(`    notify yes;`)
    if (notifyList) lines.push(`    also-notify { ${notifyList} };`)
    lines.push(`};`)
    lines.push('')
  }

  await writeConf(confPath, lines.join('\n'))
}

export async function regenerateNamedConf(zones: string[]): Promise<void> {
  await writePrimaryConf(zones)

  await rndcReconfig(PRIMARY_HOST, RNDC_PORT).catch(err =>
    console.error(`[namedConf] rndc reconfig ${PRIMARY_HOST} failed:`, err.message)
  )
}
