import { promises as dns } from 'dns'

export interface SoaTemplate {
  mname: string
  rname: string
  refresh: number
  retry: number
  expire: number
  minimum_ttl: number
}

export interface DnsRecord {
  name: string
  type: string
  ttl: number | null
  priority: number | null
  weight: number | null
  port: number | null
  value: string
}

export interface Domain {
  fqdn: string
  default_ttl: number
}

/**
 * Ensures a hostname value ends with a trailing dot (makes it FQDN in BIND).
 * Leaves "@" and relative labels untouched.
 */
function fqdn(v: string): string {
  if (v === '@' || v === '') return v
  return v.endsWith('.') ? v : `${v}.`
}

/**
 * Splits a TXT string into 255-byte chunks and wraps each in double quotes.
 * BIND requires TXT rdata strings ≤ 255 bytes per segment.
 */
function formatTxt(raw: string): string {
  // Remove surrounding quotes if the stored value already has them
  const stripped = raw.replace(/^"|"$/g, '')
  const chunks: string[] = []
  for (let i = 0; i < stripped.length; i += 255) {
    chunks.push(`"${stripped.slice(i, i + 255)}"`)
  }
  return chunks.join(' ')
}

/**
 * Resolves an ALIAS record's target to synthesized A/AAAA zone lines.
 * resolve4 failure throws (fails the zone render job).
 * resolve6 failure is silently ignored (IPv4-only targets are valid).
 */
async function resolveAlias(rec: DnsRecord, defaultTtl: number): Promise<string[]> {
  const host = rec.value.endsWith('.') ? rec.value.slice(0, -1) : rec.value
  const ttl = rec.ttl ?? defaultTtl
  const name = rec.name === '@' ? '@' : rec.name
  const lines: string[] = []

  const v4 = await dns.resolve4(host)
  for (const ip of v4) lines.push(`${name} ${ttl} IN A ${ip}`)

  try {
    const v6 = await dns.resolve6(host)
    for (const ip of v6) lines.push(`${name} ${ttl} IN AAAA ${ip}`)
  } catch { /* IPv4-only target */ }

  return lines
}

/**
 * Renders a single dns_record row into one or more zone file lines.
 */
function renderRecord(rec: DnsRecord, defaultTtl: number): string {
  const ttl = rec.ttl ?? defaultTtl
  const name = rec.name === '@' ? '@' : rec.name

  switch (rec.type) {
    case 'A':
    case 'AAAA':
    case 'PTR':
      return `${name} ${ttl} IN ${rec.type} ${rec.value}`

    case 'CNAME':
    case 'NS':
      return `${name} ${ttl} IN ${rec.type} ${fqdn(rec.value)}`

    case 'MX':
      return `${name} ${ttl} IN MX ${rec.priority ?? 10} ${fqdn(rec.value)}`

    case 'TXT':
      return `${name} ${ttl} IN TXT ${formatTxt(rec.value)}`

    case 'SRV':
      // value = target hostname; priority/weight/port separate columns
      return `${name} ${ttl} IN SRV ${rec.priority ?? 0} ${rec.weight ?? 0} ${rec.port ?? 0} ${fqdn(rec.value)}`

    case 'CAA':
    case 'TLSA':
    case 'SSHFP':
    case 'DS':
    case 'DNSKEY':
    case 'NAPTR':
      // value is stored as full normalized rdata string
      return `${name} ${ttl} IN ${rec.type} ${rec.value}`

    default:
      return `${name} ${ttl} IN ${rec.type} ${rec.value}`
  }
}

/**
 * Renders a complete BIND zone file from domain metadata + records.
 * NS records for the zone apex are injected from nsRecords (system config), not from the DB.
 * ALIAS records are resolved to A/AAAA at render time (CNAME flattening).
 */
export async function renderZone(
  domain: Domain,
  records: DnsRecord[],
  soa: SoaTemplate,
  serial: number,
  nsRecords: string[]   // e.g. ["ns1.example.com.", "ns2.example.com."]
): Promise<string> {
  const lines: string[] = []

  lines.push(`; Zone: ${domain.fqdn}`)
  lines.push(`; Generated by INFOdns Worker at ${new Date().toISOString()}`)
  lines.push(`; DO NOT EDIT MANUALLY`)
  lines.push('')
  lines.push(`$ORIGIN ${fqdn(domain.fqdn)}`)
  lines.push(`$TTL ${domain.default_ttl}`)
  lines.push('')

  // SOA
  lines.push(`@ IN SOA ${fqdn(soa.mname)} ${fqdn(soa.rname)} (`)
  lines.push(`    ${serial}   ; serial`)
  lines.push(`    ${soa.refresh}        ; refresh`)
  lines.push(`    ${soa.retry}         ; retry`)
  lines.push(`    ${soa.expire}      ; expire`)
  lines.push(`    ${soa.minimum_ttl} ) ; minimum TTL`)
  lines.push('')

  // Apex NS records (injected from system config)
  for (const ns of nsRecords) {
    lines.push(`@ IN NS ${fqdn(ns)}`)
  }
  lines.push('')

  // Resolve ALIAS records before grouping — they emit as synthesized A/AAAA, not as ALIAS
  const aliasRecords = records.filter(r => r.type === 'ALIAS')
  const nonAliasRecords = records.filter(r => r.type !== 'ALIAS')

  const aliasLines: string[] = []
  for (const rec of aliasRecords) {
    const resolved = await resolveAlias(rec, domain.default_ttl)
    aliasLines.push(...resolved)
  }

  // User records grouped by type for readability
  const byType = new Map<string, DnsRecord[]>()
  for (const rec of nonAliasRecords) {
    const list = byType.get(rec.type) ?? []
    list.push(rec)
    byType.set(rec.type, list)
  }

  for (const [type, recs] of byType) {
    lines.push(`; ${type}`)
    for (const rec of recs) {
      lines.push(renderRecord(rec, domain.default_ttl))
    }
    lines.push('')
  }

  if (aliasLines.length > 0) {
    lines.push('; ALIAS (synthesized)')
    lines.push(...aliasLines)
    lines.push('')
  }

  return lines.join('\n')
}
